/**
 * Plan command - Creates work items in Azure DevOps using Claude with WorkIQ context.
 *
 * Workflow:
 * 1. Gathers enterprise context via WorkIQ MCP
 * 2. Claude generates a work item hierarchy (Epic → Features → Stories → Tasks)
 * 3. Creates work items in ADO via az CLI
 */

import chalk from 'chalk';
import { runPlanningSession, AgentMessage } from '../agents/claude-agent.js';
import { createWorkItem, configureAdoDefaults } from '../auth/ado-token.js';
import { config } from '../config.js';

/** Work item structure generated by Claude */
export interface WorkItemPlan {
  epic: {
    title: string;
    description: string;
  };
  features: Array<{
    title: string;
    description: string;
  }>;
  stories: Array<{
    title: string;
    description: string;
    acceptanceCriteria: string[];
    featureIndex: number; // Links to parent feature
  }>;
  tasks: Array<{
    title: string;
    description: string;
    storyIndex: number; // Links to parent story
  }>;
}

export interface PlanOptions {
  /** Topic/feature to plan */
  topic: string;
  /** ADO project name (overrides config) */
  project?: string;
  /** Dry run - don't create work items, just show the plan */
  dryRun?: boolean;
  /** Verbose output */
  verbose?: boolean;
  /** Disable WorkIQ MCP */
  noWorkiq?: boolean;
}

/**
 * Converts hierarchical work items format to flat format.
 * Handles multiple formats: workItems array, features with nested stories, etc.
 */
function convertHierarchicalToFlat(data: any): WorkItemPlan | null {
  const plan: WorkItemPlan = {
    epic: { title: '', description: '' },
    features: [],
    stories: [],
    tasks: []
  };

  // Handle epic at top level
  if (data.epic) {
    plan.epic = {
      title: data.epic.title || '',
      description: data.epic.description || ''
    };
  }

  // Handle features array with nested stories
  if (data.features && Array.isArray(data.features)) {
    for (const feature of data.features) {
      const featureIndex = plan.features.length;
      plan.features.push({
        title: feature.title || '',
        description: feature.description || ''
      });

      // Check for stories nested in feature
      const featureStories = feature.stories || feature.children?.filter((c: any) =>
        c.type === 'UserStory' || c.type === 'User Story'
      ) || [];

      for (const story of featureStories) {
        const storyIndex = plan.stories.length;
        plan.stories.push({
          title: story.title || '',
          description: story.description || '',
          acceptanceCriteria: story.acceptanceCriteria || [],
          featureIndex
        });

        // Check for tasks nested in story
        const storyTasks = story.tasks || story.children?.filter((c: any) =>
          c.type === 'Task'
        ) || [];

        for (const task of storyTasks) {
          // Handle task as string or object
          if (typeof task === 'string') {
            plan.tasks.push({
              title: task,
              description: '',
              storyIndex
            });
          } else {
            plan.tasks.push({
              title: task.title || '',
              description: task.description || '',
              storyIndex
            });
          }
        }
      }
    }
  }

  // Handle workItems array format (type: Epic with children)
  const workItems = data.workItems || [];
  for (const item of workItems) {
    if (item.type === 'Epic') {
      plan.epic = {
        title: item.title || '',
        description: item.description || ''
      };

      if (item.children) {
        for (const child of item.children) {
          if (child.type === 'Feature') {
            const featureIndex = plan.features.length;
            plan.features.push({
              title: child.title || '',
              description: child.description || ''
            });

            const childStories = child.children?.filter((c: any) =>
              c.type === 'UserStory' || c.type === 'User Story'
            ) || [];

            for (const storyChild of childStories) {
              const storyIndex = plan.stories.length;
              plan.stories.push({
                title: storyChild.title || '',
                description: storyChild.description || '',
                acceptanceCriteria: storyChild.acceptanceCriteria || [],
                featureIndex
              });

              const taskChildren = storyChild.children?.filter((c: any) =>
                c.type === 'Task'
              ) || [];

              for (const taskChild of taskChildren) {
                plan.tasks.push({
                  title: taskChild.title || '',
                  description: taskChild.description || '',
                  storyIndex
                });
              }
            }
          }
        }
      }
    }
  }

  return plan.epic.title ? plan : null;
}

/**
 * Extracts the work item plan JSON from Claude's response.
 */
function extractWorkItemPlan(messages: AgentMessage[]): WorkItemPlan | null {
  const assistantContent = messages
    .filter(m => m.type === 'assistant')
    .map(m => m.content)
    .join('\n\n');

  // Look for JSON block in the response
  const jsonMatch = assistantContent.match(/```json\s*([\s\S]*?)\s*```/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[1]);

      // Check if it's the flat format we expect
      if (parsed.epic && parsed.features && parsed.stories && parsed.tasks) {
        return parsed as WorkItemPlan;
      }

      // Check if it's hierarchical format (workItems array or type: Epic)
      if (parsed.workItems || parsed.type === 'Epic') {
        return convertHierarchicalToFlat(parsed);
      }

      // Try to use as-is
      return parsed as WorkItemPlan;
    } catch (e) {
      console.error(chalk.yellow('Warning: Failed to parse work item JSON'));
    }
  }

  // Try to find raw JSON object with flat format
  const rawJsonMatch = assistantContent.match(/\{[\s\S]*"epic"[\s\S]*"features"[\s\S]*\}/);
  if (rawJsonMatch) {
    try {
      return JSON.parse(rawJsonMatch[0]) as WorkItemPlan;
    } catch (e) {
      // Ignore parse errors
    }
  }

  return null;
}

/**
 * Displays the work item plan in a readable format.
 */
function displayPlan(plan: WorkItemPlan): void {
  console.log(chalk.bold.blue('\n📋 Work Item Plan\n'));

  // Epic
  console.log(chalk.bold.magenta('Epic:'));
  if (plan.epic?.title) {
    console.log(`  ${plan.epic.title}`);
    console.log(chalk.dim(`  ${plan.epic.description?.slice(0, 100) || '(no description)'}...`));
  } else {
    console.log(chalk.yellow('  (Epic not defined)'));
  }

  // Features
  console.log(chalk.bold.cyan('\nFeatures:'));
  if (plan.features?.length) {
    plan.features.forEach((feature, i) => {
      console.log(`  ${i + 1}. ${feature.title}`);
    });
  } else {
    console.log(chalk.yellow('  (No features defined)'));
  }

  // Stories
  console.log(chalk.bold.green('\nUser Stories:'));
  if (plan.stories?.length) {
    plan.stories.forEach((story, i) => {
      const parentFeature = plan.features?.[story.featureIndex];
      console.log(`  ${i + 1}. ${story.title}`);
      console.log(chalk.dim(`     (under: ${parentFeature?.title || 'Unknown'})`));
    });
  } else {
    console.log(chalk.yellow('  (No stories defined)'));
  }

  // Tasks
  console.log(chalk.bold.yellow('\nTasks:'));
  if (plan.tasks?.length) {
    plan.tasks.forEach((task, i) => {
      const parentStory = plan.stories?.[task.storyIndex];
      console.log(`  ${i + 1}. ${task.title}`);
      console.log(chalk.dim(`     (under: ${parentStory?.title || 'Unknown'})`));
    });
  } else {
    console.log(chalk.yellow('  (No tasks defined)'));
  }
}

/**
 * Creates work items in Azure DevOps from the plan.
 */
async function createWorkItemsFromPlan(plan: WorkItemPlan): Promise<void> {
  console.log(chalk.bold.blue('\n🚀 Creating Work Items in ADO\n'));

  const createdIds: {
    epicId?: number;
    featureIds: number[];
    storyIds: number[];
    taskIds: number[];
  } = {
    featureIds: [],
    storyIds: [],
    taskIds: []
  };

  try {
    // Create Epic
    console.log(chalk.cyan('Creating Epic...'));
    createdIds.epicId = await createWorkItem(
      'Epic',
      plan.epic.title,
      plan.epic.description
    );
    console.log(chalk.green(`  ✓ Epic #${createdIds.epicId}: ${plan.epic.title}`));

    // Create Features (under Epic)
    console.log(chalk.cyan('\nCreating Features...'));
    for (const feature of plan.features) {
      const featureId = await createWorkItem(
        'Feature',
        feature.title,
        feature.description,
        createdIds.epicId
      );
      createdIds.featureIds.push(featureId);
      console.log(chalk.green(`  ✓ Feature #${featureId}: ${feature.title}`));
    }

    // Create User Stories (under Features)
    console.log(chalk.cyan('\nCreating User Stories...'));
    for (const story of plan.stories) {
      const parentFeatureId = createdIds.featureIds[story.featureIndex];
      const description = story.description + '\n\n**Acceptance Criteria:**\n' +
        story.acceptanceCriteria.map(ac => `- ${ac}`).join('\n');

      const storyId = await createWorkItem(
        'User Story',
        story.title,
        description,
        parentFeatureId
      );
      createdIds.storyIds.push(storyId);
      console.log(chalk.green(`  ✓ Story #${storyId}: ${story.title}`));
    }

    // Create Tasks (under Stories)
    console.log(chalk.cyan('\nCreating Tasks...'));
    for (const task of plan.tasks) {
      const parentStoryId = createdIds.storyIds[task.storyIndex];

      const taskId = await createWorkItem(
        'Task',
        task.title,
        task.description,
        parentStoryId
      );
      createdIds.taskIds.push(taskId);
      console.log(chalk.green(`  ✓ Task #${taskId}: ${task.title}`));
    }

    // Summary
    console.log(chalk.bold.green('\n✅ Work items created successfully!'));
    console.log(chalk.dim(`   Epic: #${createdIds.epicId}`));
    console.log(chalk.dim(`   Features: ${createdIds.featureIds.length}`));
    console.log(chalk.dim(`   Stories: ${createdIds.storyIds.length}`));
    console.log(chalk.dim(`   Tasks: ${createdIds.taskIds.length}`));

  } catch (error) {
    console.error(chalk.red('\n❌ Failed to create work items:'));
    console.error(chalk.red(error instanceof Error ? error.message : String(error)));
    throw error;
  }
}

/**
 * Runs the plan command.
 *
 * @param options - Plan command options
 */
export async function runPlanCommand(options: PlanOptions): Promise<void> {
  const { topic, project, dryRun = false, verbose = false, noWorkiq = false } = options;
  const useWorkIQ = !noWorkiq;

  console.log(chalk.bold.blue('\n📝 Planning Session\n'));
  console.log(chalk.gray(`Topic: ${topic}`));
  console.log(chalk.gray(`Project: ${project || config.adoProject || '(not set)'}`));
  console.log(chalk.gray(`Mode: ${dryRun ? 'Dry Run (no items created)' : 'Create Work Items'}`));
  if (useWorkIQ) {
    console.log(chalk.gray('Using WorkIQ for enterprise context gathering\n'));
  } else {
    console.log(chalk.yellow('WorkIQ disabled - running without enterprise context\n'));
  }
  console.log(chalk.dim('─'.repeat(60)));

  // Configure ADO defaults if project is specified
  const targetProject = project || config.adoProject;
  if (targetProject && config.adoOrgUrl && !dryRun) {
    try {
      await configureAdoDefaults(config.adoOrgUrl, targetProject);
    } catch (error) {
      console.warn(chalk.yellow('Warning: Could not configure ADO defaults'));
    }
  }

  const collectedMessages: AgentMessage[] = [];

  try {
    // Run the planning session
    for await (const message of runPlanningSession(topic, useWorkIQ)) {
      collectedMessages.push(message);

      if (verbose && message.type === 'assistant') {
        console.log(message.content);
      } else if (message.type === 'tool_use' && message.toolName === 'ask_work_iq') {
        console.log(chalk.cyan(`  🔍 Querying WorkIQ...`));
      }
    }

    // Extract the work item plan
    const plan = extractWorkItemPlan(collectedMessages);

    if (!plan) {
      console.log(chalk.yellow('\n⚠️  Could not extract work item plan from response.'));
      console.log(chalk.dim('Try running with --verbose to see the full response.'));
      return;
    }

    // Display the plan
    displayPlan(plan);

    // Create work items (unless dry run)
    if (!dryRun) {
      if (!config.adoOrgUrl || !targetProject) {
        console.log(chalk.yellow('\n⚠️  ADO_ORG_URL and ADO_PROJECT must be set to create work items.'));
        console.log(chalk.dim('Set these environment variables or use --dry-run to preview.'));
        return;
      }

      await createWorkItemsFromPlan(plan);
    } else {
      console.log(chalk.dim('\n(Dry run - no work items created)'));
    }

  } catch (error) {
    console.error(chalk.red('\n❌ Planning session failed:'));
    console.error(chalk.red(error instanceof Error ? error.message : String(error)));
    process.exit(1);
  }
}
